Feature - move pil licence number to profile
UKHomeOffice/asl-search pull request #51
Opened 2020-08-26 14:02 UTC by joefitter

* update indexer and search to use pilLicenceNumber from profile

2020-08-26 14:03 UTC, joefitter commented
WIP until the https://github.com/UKHomeOffice/asl-schema/pull/358 migration has run, and related PRs merged

2020-08-26 14:04 UTC, lennym approved these changes

2020-08-26 14:06 UTC, lennym requested changes
I can't add a comment or a suggestion because it's not in the diff, but the arguments for `withGraphFetched` on L116 of lib/indexers/profiles/index.js should have `pil` removed.

2020-08-26 14:26 UTC, joefitter commented
ah ok, thanks

2020-09-02 11:26 UTC, wheelsandcogs commented on lib/indexers/profiles/index.js
> -                }
Does this not need to become a mapping on `pilLicenceNumber` ?

2020-09-02 11:44 UTC, merged